log:
    # default = notice
    level: notice
    # default = "/var/log/resque-serial.log"
    path: "/var/log/resque-serial.log"
    # the application that sends the data, used as the "type" field of logstash
    application_name: "resque-v3"
    # the system/machine name, used as the "source" field of logstash, defaults to the hostname of the machine
    system_name: ""
    # prefix for extra keys inside logstash "fields"
    extra_prefix: ""
    # prefix for context keys inside logstash "fields", defaults to "ctxt_"
    context_prefix: "ctxt_"
    # the logstash format version to use, defaults to 0
    logstash_version: 0

statsd:
    # default = localhost
    host: "localhost"
    # default = 8125
    port: 8125
    # socket connection timeout in seconds, default = 3
    connect_timeout: 3

redis:
    # default = localhost
    hostname: localhost
    # default = 6379
    port: 6379

# {sourceId} will be replaced with source ID provided by job
task_include_path: "/opt/qu/qu/apps/versions/la/"

# default = 3
fail_retries: 3

# MANDATORY
queues:
    example_queue:
        # MANDATORY <INT>
        worker_count: 2
        # MANDATORY <BOOL>
        blocking: true
        # MANDATORY <INT> (seconds)
        interval: 3