# default = notice
log_level: notice
# default = "/var/log/resque-serial.log"
log_path: "/var/log/resque-serial.log"

redis:
    # default = localhost
    hostname: localhost
    # default = 6379
    port: 6379

# {sourceId} will be replaced with source ID provided by job
task_include_path: "/opt/qu/qu/apps/versions/la/"

# default = 3
fail_retries: 3

# MANDATORY
queues:
    example_queue:
        # MANDATORY <INT>
        worker_count: 2
        # MANDATORY <BOOL>
        blocking: true
        # MANDATORY <INT> (seconds)
        interval: 3