# MANDATORY <STRING> instance id /^[a-zA-Z0-9_]+$/ (must be unique for each resque instance)
node_id: "lokal"

log:
    # default = notice
    level: debug
    # default = "/var/log/resque-serial.log"
    path: "/var/log/resque-serial.log"
    # the application that sends the data, used as the "type" field of logstash
    application_name: "resque-v4"
    # the system/machine name, used as the "source" field of logstash, defaults to the hostname of the machine
    system_name: ""
    # prefix for extra keys inside logstash "fields"
    extra_prefix: ""
    # prefix for context keys inside logstash "fields", defaults to "ctxt_"
    context_prefix: "ctxt_"
    # the logstash format version to use, defaults to 0
    logstash_version: 1

statsd:
    # default = localhost
    host: "localhost"
    # default = 8125
    port: 8125
    # socket connection timeout in seconds, default = 3
    connect_timeout: 3

redis:
    # default = localhost
    hostname: localhost
    # default = 6379
    port: 6379

# {sourceId} will be replaced with source ID provided by job
task_include_path: "/opt/qu/qu/apps/versions/la/"

allocators:
    # default = 0
    job-count: 1
    # default = 0
    batch-count: 1

pools:
    static:
        static_1:
            # MANDATORY <INT>
            worker_count: 2
        static_2:
            # MANDATORY <INT>
            worker_count: 2
        static_3:
            # MANDATORY <INT>
            worker_count: 2
    batch:
        batch_1:
            # MANDATORY <INT>
            unit_count: 2
            # MANDATORY <INT>
            workers_per_unit: 1
        batch_2:
            # MANDATORY <INT>
            unit_count: 1
            # MANDATORY <INT>
            workers_per_unit: 2



mapping:
    static:
        default:
            # MANDATORY <STRING>
            default: static_1
        test_source:
            test_job: static_2
    batch:
        default:
            # MANDATORY <STRING>
            default: batch_1
        test_source:
            test_job: batch_2
