# default = notice
log_level: debug
# default = "/var/log/resque-serial.log"
log_path: "/home/dmolnar/tmp/resque-serial.log"

redis:
    # default = localhost
    hostname: localhost
    # default = 6379
    port: 6379

task_include_path: "/opt/qu/qu/apps/versions/la/"

# MANDATORY
queues:
    example_queue:
        # MANDATORY <INT>
        worker_count: 2
        # MANDATORY <BOOL>
        blocking: true
        serial:
            # MANDATORY <INT>
            max_workers: 5
            # MANDATORY <INT>
            max_subqueues: 5